//! Custom slash commands and subagent definitions, written once under
//! `.agents/` and projected into each vendor's project-level directory.
//!
//! - `.agents/commands/<name>.md` (a prompt with `description` and
//!   `argument-hint` frontmatter, `$ARGUMENTS` for what follows the command)
//!   is linked from `.claude/commands/` and `.pi/prompts/`. Codex and agy
//!   have no command files of their own: their slash commands are skills,
//!   which `.agents/skills` already shares.
//! - `.agents/agents/<name>.md` (Claude Code's subagent format: `name`,
//!   `description`, optional `tools` and `model`, the prompt as body) is
//!   linked from `.claude/agents/` and written as a role file to
//!   `.codex/agents/<name>.toml`, without `tools` and `model`, whose values
//!   are Claude's.
//!
//! Hooks are not projected: each vendor sends its hooks a payload of its own
//! (tool names, input fields), so a hook written for one would misread
//! another's calls, and a hook that guards something would let it through.
//!
//! Like `rules.rs`, this never destroys a file it did not make. A link is
//! created where nothing is, or in place of a file with the same content;
//! a generated file carries [`MARKER`] on its first line and only such a
//! file is rewritten. Anything else in the way is left alone with a
//! warning. A link or generated file whose source is gone is removed.

use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::Serialize;

/// First line of every file unharness generates here.
pub const MARKER: &str = "# Generated by unharness from ";

#[derive(Clone, Copy, PartialEq, Eq)]
enum Form {
    /// A relative symlink to the source.
    Link,
    /// A Codex agent role (`name`, `description`, `developer_instructions`).
    CodexRole,
}

struct Target {
    /// Directory under `.agents/`.
    kind: &'static str,
    /// Directory under the workspace root.
    dir: &'static str,
    form: Form,
}

const TARGETS: &[Target] = &[
    Target {
        kind: "commands",
        dir: ".claude/commands",
        form: Form::Link,
    },
    Target {
        kind: "commands",
        dir: ".pi/prompts",
        form: Form::Link,
    },
    Target {
        kind: "agents",
        dir: ".claude/agents",
        form: Form::Link,
    },
    Target {
        kind: "agents",
        dir: ".codex/agents",
        form: Form::CodexRole,
    },
];

#[derive(Debug, Default)]
pub struct ProjectionReport {
    /// Links and files created or rewritten, relative to the root.
    pub written: Vec<PathBuf>,
    /// Links and generated files whose source is gone.
    pub removed: Vec<PathBuf>,
    pub warnings: Vec<String>,
}

pub fn sync_projections(root: &Path) -> Result<ProjectionReport> {
    let mut report = ProjectionReport::default();
    for kind in ["commands", "agents"] {
        let files = sources(root, kind, &mut report.warnings)?;
        for target in TARGETS.iter().filter(|t| t.kind == kind) {
            project(root, target, &files, &mut report)?;
        }
    }
    Ok(report)
}

/// What a source's file name may hold. It ends up in a path, a link and
/// the first line of a generated TOML file, a comment read back by its
/// end ([`MARKER_END`]), so only a line break could change what it says.
fn valid_name(file: &str) -> bool {
    stem(file).is_some_and(|stem| !stem.is_empty() && !stem.starts_with('.') && plain(stem))
}

/// A source's name without its one `.md` (`x.md.md` is `x.md`).
fn stem(file: &str) -> Option<&str> {
    file.strip_suffix(".md")
}

/// Neither a path separator nor a control character (a line break is
/// one), nor one that changes how the text around it is shown in a
/// warning or the marker line: zero-width and direction marks, line and
/// paragraph separators, embeddings, overrides and isolates, and the
/// byte order mark.
fn plain(name: &str) -> bool {
    !name.chars().any(|c| {
        c.is_control()
            || matches!(
                c,
                '/' | '\\'
                    | '\u{200B}'..='\u{200F}'
                    | '\u{2028}'..='\u{202E}'
                    | '\u{2060}'..='\u{2069}'
                    | '\u{FEFF}'
            )
    })
}

/// The `.md` files directly in `.agents/<kind>/`, by file name.
fn sources(root: &Path, kind: &str, warnings: &mut Vec<String>) -> Result<Vec<String>> {
    let dir = root.join(".agents").join(kind);
    let Ok(entries) = fs::read_dir(&dir) else {
        return Ok(Vec::new());
    };
    let mut names = Vec::new();
    for entry in entries {
        let entry = entry?;
        let name = entry.file_name().to_string_lossy().into_owned();
        // `is_file` follows links: a linked source is a source.
        if !name.ends_with(".md") || name.starts_with('.') || !entry.path().is_file() {
            continue;
        }
        if valid_name(&name) {
            names.push(name);
        } else {
            warnings.push(format!(
                ".agents/{kind}/{name:?} is not projected: a name may not hold a control or formatting character or '\\'"
            ));
        }
    }
    names.sort();
    Ok(names)
}

/// The link text from `dir`, where it lies relative to the root (see
/// [`placement`]), to `.agents/<kind>/<file>`.
fn link_text(dir: &Path, kind: &str, file: &str) -> PathBuf {
    let mut text = PathBuf::new();
    for _ in dir.components() {
        text.push("..");
    }
    text.join(".agents").join(kind).join(file)
}

/// Where `target.dir` lies on disk, relative to the root once links on
/// the way are followed, or why nothing may be written there. Sync runs
/// outside the sandbox, so a directory on the way that is a link out of
/// the workspace (`.codex -> ~/.codex`, which an agent can make) would
/// carry its writes there; one that leads into the workspace (`.claude ->
/// cfg/claude`) is followed. A source directory that is the target
/// (`.agents/agents -> ../.claude/agents`) would have each file replaced
/// by a link to itself.
fn placement(root: &Path, target: &Target) -> Result<PathBuf, String> {
    let real_root = fs::canonicalize(root).map_err(|e| e.to_string())?;
    let mut path = root.to_path_buf();
    let mut real = real_root.clone();
    for part in Path::new(target.dir).components() {
        path.push(part);
        let is_link = fs::symlink_metadata(&path).is_ok_and(|m| m.file_type().is_symlink());
        if !is_link {
            real.push(part);
            continue;
        }
        let shown = rel(root, &path);
        real = match fs::canonicalize(&path) {
            Ok(to) if to.starts_with(&real_root) => to,
            Ok(_) => {
                return Err(format!(
                    "{} is a symbolic link out of the workspace, and sync does not write through one",
                    shown.display()
                ));
            }
            Err(_) => {
                return Err(format!(
                    "{} is a symbolic link that leads nowhere",
                    shown.display()
                ));
            }
        };
    }
    if let (Ok(dir), Ok(source)) = (
        fs::canonicalize(root.join(target.dir)),
        fs::canonicalize(root.join(".agents").join(target.kind)),
    ) && (source.starts_with(&dir) || dir.starts_with(&source))
    {
        return Err(format!(".agents/{} is {} itself", target.kind, target.dir));
    }
    Ok(real
        .strip_prefix(&real_root)
        .map(Path::to_path_buf)
        .unwrap_or_default())
}

fn project(
    root: &Path,
    target: &Target,
    files: &[String],
    report: &mut ProjectionReport,
) -> Result<()> {
    let dir = root.join(target.dir);
    if files.is_empty() && !dir.is_dir() {
        return Ok(());
    }
    let placed = match placement(root, target) {
        Ok(placed) => placed,
        // With nothing to project there is nothing to say.
        Err(_) if files.is_empty() => return Ok(()),
        Err(why) => {
            report
                .warnings
                .push(format!("nothing is projected to {}: {why}.", target.dir));
            return Ok(());
        }
    };
    let canonical_dir = fs::canonicalize(&dir).ok();
    for file in files {
        let source = root.join(".agents").join(target.kind).join(file);
        let origin = format!(".agents/{}/{file}", target.kind);
        // A source linked to a file in the target directory is that file.
        if let (Some(dir), Ok(real)) = (&canonical_dir, fs::canonicalize(&source))
            && real.starts_with(dir)
        {
            report.warnings.push(format!(
                "{origin} is not projected to {}: it links to a file there.",
                target.dir
            ));
            continue;
        }
        match target.form {
            Form::Link => {
                let link = dir.join(file);
                let text = link_text(&placed, target.kind, file);
                ensure_link(root, &link, &text, &source, report)?;
            }
            Form::CodexRole => {
                // Every source passed `valid_name`.
                let stem = stem(file).unwrap_or(file);
                let out = dir.join(format!("{stem}.toml"));
                let content = super::read_regular(&source, true)
                    .and_then(|bytes| String::from_utf8(bytes).map_err(std::io::Error::other));
                let content = match content {
                    Ok(content) => content,
                    Err(e) => {
                        report.warnings.push(format!(
                            "{origin} is not projected to {}: it cannot be read ({e}).",
                            target.dir
                        ));
                        continue;
                    }
                };
                match codex_role(&origin, stem, &content) {
                    Ok(generated) => ensure_generated(root, &out, &generated, report)?,
                    Err(why) => report.warnings.push(format!(
                        "{origin} is not projected to {}: {why}",
                        target.dir
                    )),
                }
            }
        }
    }
    remove_stale(root, target, &placed, report)
}

fn ensure_link(
    root: &Path,
    link: &Path,
    text: &Path,
    source: &Path,
    report: &mut ProjectionReport,
) -> Result<()> {
    let shown = rel(root, link);
    if link.is_symlink() {
        if fs::read_link(link)? != text {
            report.warnings.push(format!(
                "{} links elsewhere, not to {}; leaving it in place.",
                shown.display(),
                text.display()
            ));
        }
        return Ok(());
    }
    if link.exists() {
        // Never the source itself: `project` skips a source that resolves
        // into the target directory. Only regular files are read.
        let same = match (
            super::read_regular(link, false),
            super::read_regular(source, true),
        ) {
            (Ok(there), Ok(source)) => there == source,
            _ => false,
        };
        if same {
            fs::remove_file(link)?;
        } else {
            report.warnings.push(format!(
                "{} differs from {}; leaving it in place to prevent data loss.",
                shown.display(),
                rel(root, source).display()
            ));
            return Ok(());
        }
    }
    if let Some(parent) = link.parent() {
        fs::create_dir_all(parent)?;
    }
    #[cfg(unix)]
    std::os::unix::fs::symlink(text, link)?;
    report.written.push(shown);
    Ok(())
}

fn ensure_generated(
    root: &Path,
    out: &Path,
    content: &str,
    report: &mut ProjectionReport,
) -> Result<()> {
    use std::io::{ErrorKind, Write};
    let shown = rel(root, out);
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent)?;
    }
    // What is there is read without following a link, and replaced only
    // when it is ours and differs, so a role made read-only that is up to
    // date is left alone. The new content goes to a file of its own that
    // then takes the role's place: `rename` replaces a link and does not
    // follow it, and a write that fails part-way leaves the old role.
    let mut permissions = None;
    match super::open_regular(out, false) {
        Ok(file) => {
            let current = super::read_capped(&file)
                .ok()
                .and_then(|bytes| String::from_utf8(bytes).ok());
            if current.as_deref() == Some(content) {
                return Ok(());
            }
            if !current.is_some_and(|current| current.starts_with(MARKER)) {
                report.warnings.push(format!(
                    "{} was not written by unharness; leaving it in place to prevent data loss.",
                    shown.display()
                ));
                return Ok(());
            }
            permissions = file.metadata().ok().map(|m| m.permissions());
        }
        Err(e) if e.kind() == ErrorKind::NotFound => {}
        Err(e) => {
            let why = if super::is_link_error(&e) {
                "is a link, not written by unharness".to_string()
            } else {
                format!("cannot be opened ({e})")
            };
            report
                .warnings
                .push(format!("{} {why}; leaving it in place.", shown.display()));
            return Ok(());
        }
    }
    // Hidden and not `.toml`: never a source, a role or a projection.
    let temp = out.with_file_name(format!(".unharness-{}.tmp", std::process::id()));
    super::create_new_with(&temp, |file| {
        file.write_all(content.as_bytes())?;
        match permissions {
            Some(permissions) => file.set_permissions(permissions),
            None => Ok(()),
        }
    })
    .with_context(|| format!("write {}", temp.display()))?;
    fs::rename(&temp, out)
        .inspect_err(|_| {
            let _ = fs::remove_file(&temp);
        })
        .with_context(|| format!("replace {}", out.display()))?;
    report.written.push(shown);
    Ok(())
}

/// Removes the links into `.agents/<kind>/` and the generated files whose
/// source no longer exists.
fn remove_stale(
    root: &Path,
    target: &Target,
    placed: &Path,
    report: &mut ProjectionReport,
) -> Result<()> {
    let dir = root.join(target.dir);
    let Ok(entries) = fs::read_dir(&dir) else {
        return Ok(());
    };
    let sources = root.join(".agents").join(target.kind);
    // Gone: not a source that cannot be read, or a link that leads nowhere.
    let gone = |file: &OsStr| fs::symlink_metadata(sources.join(file)).is_err();
    let ours = link_text(placed, target.kind, "");
    for entry in entries {
        let path = entry?.path();
        let stale = if path.is_symlink() {
            let text = fs::read_link(&path)?;
            text.parent() == Some(ours.as_path()) && text.file_name().is_some_and(gone)
        } else if target.form == Form::CodexRole && path.is_file() {
            generated_from(&path)
                .and_then(|origin| {
                    let file = origin
                        .strip_prefix(".agents/")?
                        .strip_prefix(target.kind)?
                        .strip_prefix('/')?;
                    // Any file directly in that directory, whatever the
                    // rule for names was when the role was generated.
                    (plain(file) && !matches!(file, "" | "." | ".."))
                        .then(|| gone(OsStr::new(file)))
                })
                .unwrap_or(false)
        } else {
            false
        };
        if stale {
            fs::remove_file(&path)?;
            report.removed.push(rel(root, &path));
        }
    }
    Ok(())
}

/// What follows the source's path on a generated file's first line.
const MARKER_END: &str = "; edit that file, this one is rewritten.";

/// The source a generated file names on its first line.
fn generated_from(path: &Path) -> Option<String> {
    let content = String::from_utf8(super::read_regular(path, false).ok()?).ok()?;
    let first = content.lines().next()?;
    let origin = first.strip_prefix(MARKER)?.strip_suffix(MARKER_END)?;
    Some(origin.to_string())
}

fn rel(root: &Path, path: &Path) -> PathBuf {
    path.strip_prefix(root).unwrap_or(path).to_path_buf()
}

/// YAML frontmatter and body of a Markdown definition.
fn split_frontmatter(content: &str) -> Result<(serde_yaml::Mapping, &str), String> {
    let Some(rest) = content
        .strip_prefix("---\n")
        .or_else(|| content.strip_prefix("---\r\n"))
    else {
        return Ok((serde_yaml::Mapping::new(), content));
    };
    // The first line that is `---` and nothing else closes it.
    let mut offset = 0;
    let mut close = None;
    for line in rest.split_inclusive('\n') {
        if line.trim_end_matches(['\r', '\n']) == "---" {
            close = Some((offset, offset + line.len()));
            break;
        }
        offset += line.len();
    }
    let Some((end, body_start)) = close else {
        return Err("its frontmatter has no closing `---`".into());
    };
    let (yaml, body) = (&rest[..end], &rest[body_start..]);
    if yaml.trim().is_empty() {
        return Ok((serde_yaml::Mapping::new(), body));
    }
    let map = serde_yaml::from_str::<serde_yaml::Mapping>(yaml)
        .map_err(|e| format!("its frontmatter does not parse ({e})"))?;
    Ok((map, body))
}

#[derive(Serialize)]
struct CodexRole<'a> {
    name: &'a str,
    description: &'a str,
    developer_instructions: &'a str,
}

/// A Codex agent role file for a Claude-format subagent definition. Codex
/// ignores a role without a name, a description or instructions.
fn codex_role(origin: &str, stem: &str, content: &str) -> Result<String, String> {
    let (front, body) = split_frontmatter(content)?;
    let text = |key: &str| front.get(key).and_then(|v| v.as_str()).map(str::trim);
    let name = text("name").filter(|n| !n.is_empty()).unwrap_or(stem);
    let description = text("description")
        .filter(|d| !d.is_empty())
        .ok_or("it has no `description`")?;
    let instructions = body.trim();
    if instructions.is_empty() {
        return Err("it has no prompt after the frontmatter".into());
    }
    let role = toml::to_string(&CodexRole {
        name,
        description,
        developer_instructions: instructions,
    })
    .map_err(|e| e.to_string())?;
    Ok(format!("{MARKER}{origin}{MARKER_END}\n{role}"))
}

#[cfg(all(test, unix))]
mod tests {
    use super::*;

    const AGENT: &str = "---\nname: reviewer\ndescription: Reviews code\ntools: Read, Grep\nmodel: haiku\n---\n\nYou review code.\nBe brief.\n";

    fn write(root: &Path, rel: &str, content: &str) {
        let path = root.join(rel);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, content).unwrap();
    }

    #[test]
    fn nothing_under_agents_creates_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let r = sync_projections(dir.path()).unwrap();
        assert!(r.written.is_empty() && r.warnings.is_empty());
        for d in [".claude", ".pi", ".codex"] {
            assert!(!dir.path().join(d).exists());
        }
    }

    #[test]
    fn commands_and_agents_are_projected_once() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(root, ".agents/commands/fix.md", "Fix $ARGUMENTS\n");
        write(root, ".agents/agents/reviewer.md", AGENT);
        // Not sources: another extension, a hidden file, a subdirectory.
        write(root, ".agents/commands/notes.txt", "x");
        write(root, ".agents/commands/.draft.md", "x");
        write(root, ".agents/commands/sub/deep.md", "x");

        let r = sync_projections(root).unwrap();
        assert!(r.warnings.is_empty(), "{:?}", r.warnings);
        let mut written: Vec<_> = r.written.iter().map(|p| p.display().to_string()).collect();
        written.sort();
        assert_eq!(
            written,
            [
                ".claude/agents/reviewer.md",
                ".claude/commands/fix.md",
                ".codex/agents/reviewer.toml",
                ".pi/prompts/fix.md",
            ]
        );
        assert_eq!(
            fs::read_link(root.join(".claude/commands/fix.md")).unwrap(),
            Path::new("../../.agents/commands/fix.md")
        );
        assert_eq!(
            fs::read_to_string(root.join(".pi/prompts/fix.md")).unwrap(),
            "Fix $ARGUMENTS\n"
        );
        let role = fs::read_to_string(root.join(".codex/agents/reviewer.toml")).unwrap();
        assert!(role.starts_with(MARKER), "{role}");
        let parsed: toml::Table = toml::from_str(&role).unwrap();
        assert_eq!(parsed["name"].as_str(), Some("reviewer"));
        assert_eq!(parsed["description"].as_str(), Some("Reviews code"));
        assert_eq!(
            parsed["developer_instructions"].as_str(),
            Some("You review code.\nBe brief.")
        );
        assert!(!parsed.contains_key("tools") && !parsed.contains_key("model"));

        let again = sync_projections(root).unwrap();
        assert!(again.written.is_empty() && again.removed.is_empty() && again.warnings.is_empty());
    }

    #[test]
    fn a_users_own_file_is_never_replaced() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(root, ".agents/commands/fix.md", "Fix $ARGUMENTS\n");
        write(root, ".agents/commands/same.md", "Same\n");
        write(root, ".agents/agents/reviewer.md", AGENT);
        write(root, ".claude/commands/fix.md", "My own fix\n");
        write(root, ".claude/commands/same.md", "Same\n");
        write(root, ".codex/agents/reviewer.toml", "name = \"mine\"\n");
        write(root, "elsewhere.md", "x");
        fs::create_dir_all(root.join(".pi/prompts")).unwrap();
        std::os::unix::fs::symlink("../../elsewhere.md", root.join(".pi/prompts/fix.md")).unwrap();

        let r = sync_projections(root).unwrap();
        assert_eq!(r.warnings.len(), 3, "{:?}", r.warnings);
        assert_eq!(
            fs::read_to_string(root.join(".claude/commands/fix.md")).unwrap(),
            "My own fix\n"
        );
        assert!(!root.join(".claude/commands/fix.md").is_symlink());
        assert_eq!(
            fs::read_to_string(root.join(".codex/agents/reviewer.toml")).unwrap(),
            "name = \"mine\"\n"
        );
        assert_eq!(
            fs::read_link(root.join(".pi/prompts/fix.md")).unwrap(),
            Path::new("../../elsewhere.md")
        );
        // The same content is replaced by a link.
        assert!(root.join(".claude/commands/same.md").is_symlink());
    }

    #[test]
    fn a_generated_file_follows_its_source_and_goes_with_it() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(root, ".agents/agents/reviewer.md", AGENT);
        write(root, ".agents/commands/fix.md", "Fix\n");
        sync_projections(root).unwrap();

        write(
            root,
            ".agents/agents/reviewer.md",
            &AGENT.replace("Reviews code", "Reviews diffs"),
        );
        let r = sync_projections(root).unwrap();
        assert_eq!(r.written, [PathBuf::from(".codex/agents/reviewer.toml")]);
        let role = fs::read_to_string(root.join(".codex/agents/reviewer.toml")).unwrap();
        assert!(role.contains("Reviews diffs"));

        fs::remove_file(root.join(".agents/agents/reviewer.md")).unwrap();
        fs::remove_file(root.join(".agents/commands/fix.md")).unwrap();
        // A user's file and a link of the user's own stay.
        write(root, ".codex/agents/mine.toml", "name = \"mine\"\n");
        std::os::unix::fs::symlink("gone.md", root.join(".claude/agents/dangling.md")).unwrap();
        let r = sync_projections(root).unwrap();
        let mut removed: Vec<_> = r.removed.iter().map(|p| p.display().to_string()).collect();
        removed.sort();
        assert_eq!(
            removed,
            [
                ".claude/agents/reviewer.md",
                ".claude/commands/fix.md",
                ".codex/agents/reviewer.toml",
                ".pi/prompts/fix.md",
            ]
        );
        assert!(root.join(".codex/agents/mine.toml").exists());
        assert!(root.join(".claude/agents/dangling.md").is_symlink());
    }

    #[test]
    fn an_agent_codex_cannot_take_is_named() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(root, ".agents/agents/a.md", "---\nname: a\n---\nDo it.\n");
        write(
            root,
            ".agents/agents/b.md",
            "---\nname: b\ndescription: B\n---\n",
        );
        write(root, ".agents/agents/c.md", "---\nname: [c\n---\nDo it.\n");
        let r = sync_projections(root).unwrap();
        assert_eq!(r.warnings.len(), 3, "{:?}", r.warnings);
        assert!(r.warnings[0].contains("no `description`"));
        assert!(r.warnings[1].contains("no prompt"));
        assert!(r.warnings[2].contains("does not parse"));
        // Claude gets them all: it judges them itself.
        assert!(root.join(".claude/agents/a.md").is_symlink());
        assert!(!root.join(".codex/agents").exists());
    }

    #[test]
    fn a_source_that_is_the_target_is_never_replaced() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        // The whole directory shared backwards.
        write(root, ".claude/agents/reviewer.md", AGENT);
        fs::create_dir_all(root.join(".agents")).unwrap();
        std::os::unix::fs::symlink("../.claude/agents", root.join(".agents/agents")).unwrap();
        // One file shared backwards.
        write(root, ".claude/commands/fix.md", "Fix $ARGUMENTS\n");
        fs::create_dir_all(root.join(".agents/commands")).unwrap();
        std::os::unix::fs::symlink(
            "../../.claude/commands/fix.md",
            root.join(".agents/commands/fix.md"),
        )
        .unwrap();

        for _ in 0..2 {
            let r = sync_projections(root).unwrap();
            assert!(r.removed.is_empty(), "{:?}", r.removed);
            assert!(
                r.warnings.iter().any(|w| w.contains(".claude/agents")),
                "{:?}",
                r.warnings
            );
            assert!(
                r.warnings
                    .iter()
                    .any(|w| w.contains("links to a file there")),
                "{:?}",
                r.warnings
            );
            for (file, content) in [
                (".claude/agents/reviewer.md", AGENT),
                (".claude/commands/fix.md", "Fix $ARGUMENTS\n"),
            ] {
                let path = root.join(file);
                assert!(!path.is_symlink(), "{file}");
                assert_eq!(fs::read_to_string(&path).unwrap(), content);
            }
        }
        // The other harnesses still get them.
        assert!(root.join(".codex/agents/reviewer.toml").is_file());
        assert_eq!(
            fs::read_to_string(root.join(".pi/prompts/fix.md")).unwrap(),
            "Fix $ARGUMENTS\n"
        );
    }

    #[test]
    fn nothing_is_written_through_a_linked_directory() {
        let outside = tempfile::tempdir().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(root, ".agents/agents/evil.md", AGENT);
        write(root, ".agents/commands/fix.md", "Fix\n");
        // `.codex -> ~/.codex`, `.claude/commands -> elsewhere`.
        std::os::unix::fs::symlink(outside.path(), root.join(".codex")).unwrap();
        fs::create_dir_all(root.join(".claude")).unwrap();
        fs::create_dir_all(outside.path().join("commands")).unwrap();
        std::os::unix::fs::symlink(
            outside.path().join("commands"),
            root.join(".claude/commands"),
        )
        .unwrap();

        let r = sync_projections(root).unwrap();
        assert!(!outside.path().join("agents").exists());
        assert_eq!(
            fs::read_dir(outside.path().join("commands"))
                .unwrap()
                .count(),
            0
        );
        let refused: Vec<_> = r
            .warnings
            .iter()
            .filter(|w| w.contains("symbolic link"))
            .collect();
        assert_eq!(refused.len(), 2, "{:?}", r.warnings);
        // Directories that are not links still get theirs.
        assert!(root.join(".claude/agents/evil.md").is_symlink());
        assert!(root.join(".pi/prompts/fix.md").is_symlink());
    }

    #[test]
    fn a_linked_directory_with_nothing_to_project_is_quiet() {
        let outside = tempfile::tempdir().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        fs::create_dir_all(outside.path().join("commands")).unwrap();
        fs::create_dir_all(outside.path().join("agents")).unwrap();
        std::os::unix::fs::symlink(outside.path(), root.join(".claude")).unwrap();
        let r = sync_projections(root).unwrap();
        assert!(r.warnings.is_empty(), "{:?}", r.warnings);
        // An empty source directory is no source either.
        fs::create_dir_all(root.join(".agents/commands")).unwrap();
        let r = sync_projections(root).unwrap();
        assert!(r.warnings.is_empty(), "{:?}", r.warnings);
    }

    #[test]
    fn a_link_into_the_workspace_is_followed() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(root, ".agents/commands/fix.md", "Fix\n");
        write(root, ".agents/agents/reviewer.md", AGENT);
        fs::create_dir_all(root.join("cfg/claude")).unwrap();
        std::os::unix::fs::symlink("cfg/claude", root.join(".claude")).unwrap();
        fs::create_dir_all(root.join("cfg/codex")).unwrap();
        std::os::unix::fs::symlink(root.join("cfg/codex"), root.join(".codex")).unwrap();

        let r = sync_projections(root).unwrap();
        assert!(r.warnings.is_empty(), "{:?}", r.warnings);
        // The link is relative to where it lies.
        let link = root.join("cfg/claude/commands/fix.md");
        assert_eq!(
            fs::read_link(&link).unwrap(),
            Path::new("../../../.agents/commands/fix.md")
        );
        assert_eq!(fs::read_to_string(&link).unwrap(), "Fix\n");
        assert_eq!(
            fs::read_to_string(root.join(".claude/agents/reviewer.md")).unwrap(),
            AGENT
        );
        assert!(root.join("cfg/codex/agents/reviewer.toml").is_file());

        let again = sync_projections(root).unwrap();
        assert!(again.written.is_empty() && again.removed.is_empty() && again.warnings.is_empty());
        fs::remove_file(root.join(".agents/commands/fix.md")).unwrap();
        let r = sync_projections(root).unwrap();
        assert!(
            r.removed
                .contains(&PathBuf::from(".claude/commands/fix.md"))
        );
        assert!(!link.is_symlink());

        // A link that leads nowhere is not followed.
        write(root, ".agents/commands/fix.md", "Fix\n");
        fs::remove_file(root.join(".claude")).unwrap();
        std::os::unix::fs::symlink("cfg/none", root.join(".claude")).unwrap();
        let r = sync_projections(root).unwrap();
        assert!(!root.join("cfg/none").exists());
        assert!(
            r.warnings.iter().any(|w| w.contains("leads nowhere")),
            "{:?}",
            r.warnings
        );
    }

    #[test]
    fn a_generated_file_is_never_written_through_a_link() {
        let outside = tempfile::tempdir().unwrap();
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(root, ".agents/agents/reviewer.md", AGENT);
        fs::create_dir_all(root.join(".codex/agents")).unwrap();
        // A file outside that reads as one unharness generated: only the
        // open, which does not follow the link, keeps it from a rewrite.
        let target = outside.path().join("config.toml");
        let looks_generated =
            format!("{MARKER}.agents/agents/reviewer.md{MARKER_END}\nname = \"old\"\n");
        fs::write(&target, &looks_generated).unwrap();
        std::os::unix::fs::symlink(&target, root.join(".codex/agents/reviewer.toml")).unwrap();
        let r = sync_projections(root).unwrap();
        assert_eq!(r.warnings.len(), 1, "{:?}", r.warnings);
        assert!(r.warnings[0].contains("is a link"), "{:?}", r.warnings);
        assert!(r.written.iter().all(|p| !p.starts_with(".codex")));
        assert_eq!(fs::read_to_string(&target).unwrap(), looks_generated);
    }

    #[test]
    fn a_name_that_could_break_a_file_is_not_projected() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let injected = "x\nmodel_reasoning_effort = \"low\"\n#.md";
        write(root, &format!(".agents/agents/{injected}"), AGENT);
        write(root, ".agents/agents/a\\b.md", AGENT);
        write(root, ".agents/agents/re.view_er-2.md", AGENT);
        let r = sync_projections(root).unwrap();
        assert_eq!(r.warnings.len(), 2, "{:?}", r.warnings);
        assert!(r.warnings.iter().all(|w| w.contains("a name may not hold")));
        let names: Vec<_> = fs::read_dir(root.join(".codex/agents"))
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        assert_eq!(names, ["re.view_er-2.toml"]);
        assert_eq!(
            fs::read_dir(root.join(".claude/agents")).unwrap().count(),
            1
        );
        // A role that is kept stays kept.
        let again = sync_projections(root).unwrap();
        assert!(again.removed.is_empty() && again.written.is_empty());
    }

    #[test]
    fn a_name_in_any_language_keeps_its_role() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        // The marker line is read back by its end, so a ';' cannot cut it.
        let file = "rö view; x.md";
        write(root, &format!(".agents/agents/{file}"), AGENT);
        let role = root.join(".codex/agents/rö view; x.toml");
        let r = sync_projections(root).unwrap();
        assert!(r.warnings.is_empty(), "{:?}", r.warnings);
        assert!(role.is_file());
        assert_eq!(
            generated_from(&role).as_deref(),
            Some(".agents/agents/rö view; x.md")
        );
        assert!(root.join(".claude/agents").join(file).is_symlink());
        let again = sync_projections(root).unwrap();
        assert!(again.removed.is_empty() && again.written.is_empty() && again.warnings.is_empty());
        assert!(role.is_file());

        // Its role goes with it, as do ones generated under other rules
        // for names (`.x` is not a name now).
        let older: Vec<_> = ["a;b", ".x"]
            .iter()
            .map(|stem| {
                let path = root.join(format!(".codex/agents/{stem}.toml"));
                let origin = format!(".agents/agents/{stem}.md");
                fs::write(
                    &path,
                    format!("{MARKER}{origin}{MARKER_END}\nname = \"x\"\n"),
                )
                .unwrap();
                path
            })
            .collect();
        fs::remove_file(root.join(".agents/agents").join(file)).unwrap();
        let r = sync_projections(root).unwrap();
        assert_eq!(r.removed.len(), 4, "{:?}", r.removed);
        assert!(!role.exists() && older.iter().all(|p| !p.exists()));
    }

    #[test]
    fn a_name_that_would_be_shown_misleadingly_is_not_projected() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        let names = [
            "a\u{202E}dm.md",
            "a\u{2028}b.md",
            "a\u{200B}b.md",
            "a\u{2066}b.md",
            "\u{FEFF}a.md",
        ];
        for name in names {
            write(root, &format!(".agents/agents/{name}"), AGENT);
        }
        let r = sync_projections(root).unwrap();
        assert_eq!(r.warnings.len(), names.len(), "{:?}", r.warnings);
        // Shown escaped.
        assert!(
            r.warnings.iter().any(|w| w.contains("a\\u{202e}dm.md")),
            "{:?}",
            r.warnings
        );
        assert!(r.written.is_empty(), "{:?}", r.written);

        // Nor is a role naming one taken for one of ours.
        for name in names {
            fs::remove_file(root.join(".agents/agents").join(name)).unwrap();
        }
        write(root, ".agents/agents/kept.md", AGENT);
        let origin = ".agents/agents/a\u{202E}dm.md";
        write(
            root,
            ".codex/agents/a.toml",
            &format!("{MARKER}{origin}{MARKER_END}\nname = \"a\"\n"),
        );
        let role = root.join(".codex/agents/a.toml");
        let r = sync_projections(root).unwrap();
        assert!(r.removed.is_empty(), "{:?}", r.removed);
        assert!(role.is_file());
    }

    #[test]
    fn only_one_md_is_taken_off_a_name() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        // Both were x.toml, rewritten by one and then the other.
        write(root, ".agents/agents/x.md", AGENT);
        write(
            root,
            ".agents/agents/x.md.md",
            &AGENT.replace("reviewer", "other"),
        );
        sync_projections(root).unwrap();
        let again = sync_projections(root).unwrap();
        assert!(again.written.is_empty(), "{:?}", again.written);
        assert!(
            fs::read_to_string(root.join(".codex/agents/x.toml"))
                .unwrap()
                .contains("name = \"reviewer\"")
        );
        assert!(
            fs::read_to_string(root.join(".codex/agents/x.md.toml"))
                .unwrap()
                .contains("name = \"other\"")
        );
    }

    #[test]
    fn an_up_to_date_role_made_read_only_is_left_alone() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        write(root, ".agents/agents/reviewer.md", AGENT);
        sync_projections(root).unwrap();
        let role = root.join(".codex/agents/reviewer.toml");
        fs::set_permissions(&role, fs::Permissions::from_mode(0o444)).unwrap();
        // Root opens it for writing anyway.
        let writable = fs::OpenOptions::new().write(true).open(&role).is_ok();

        let r = sync_projections(root).unwrap();
        if !writable {
            assert!(r.warnings.is_empty(), "{:?}", r.warnings);
        }
        assert!(r.written.is_empty(), "{:?}", r.written);
        // One that is not up to date is replaced, and stays read-only.
        write(
            root,
            ".agents/agents/reviewer.md",
            &AGENT.replace("Reviews code", "Reviews diffs"),
        );
        let r = sync_projections(root).unwrap();
        assert!(r.warnings.is_empty(), "{:?}", r.warnings);
        assert_eq!(r.written, [PathBuf::from(".codex/agents/reviewer.toml")]);
        assert!(fs::read_to_string(&role).unwrap().contains("Reviews diffs"));
        let mode = fs::metadata(&role).unwrap().permissions().mode();
        assert_eq!(mode & 0o777, 0o444);
        // Nothing is left beside it.
        assert_eq!(fs::read_dir(root.join(".codex/agents")).unwrap().count(), 1);
    }

    #[test]
    fn only_a_regular_file_of_bounded_size_is_read() {
        use crate::sync::testing::{mkfifo, within};
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().to_path_buf();
        write(&root, ".agents/agents/reviewer.md", AGENT);
        fs::create_dir_all(root.join(".codex/agents")).unwrap();
        // Opened for reading and writing a FIFO does not block; its read does.
        mkfifo(&root.join(".codex/agents/reviewer.toml"));
        let large = format!("{AGENT}{}", "x".repeat(super::super::READ_LIMIT as usize));
        write(&root, ".agents/agents/large.md", &large);
        let r = within({
            let root = root.clone();
            move || sync_projections(&root).unwrap()
        });
        assert_eq!(r.warnings.len(), 2, "{:?}", r.warnings);
        assert!(r.warnings[0].contains("large.md") && r.warnings[0].contains("larger than"));
        assert!(
            r.warnings[1].contains("reviewer.toml") && r.warnings[1].contains("not a regular file")
        );
        assert!(!root.join(".codex/agents/large.toml").exists());
        assert!(
            !fs::symlink_metadata(root.join(".codex/agents/reviewer.toml"))
                .unwrap()
                .is_file()
        );
    }

    #[test]
    fn frontmatter_closes_on_its_own_line() {
        let (front, body) = split_frontmatter("---\n---\nBody\n").unwrap();
        assert!(front.is_empty());
        assert_eq!(body, "Body\n");
        let (front, body) = split_frontmatter("---\r\ndescription: D\r\n---\r\nBody\r\n").unwrap();
        assert_eq!(front.get("description").and_then(|v| v.as_str()), Some("D"));
        assert_eq!(body, "Body\r\n");
        // A longer rule inside a block scalar does not close it.
        let (front, body) = split_frontmatter("---\ndescription: |\n  a\n  ----\n---\nB").unwrap();
        assert_eq!(
            front.get("description").and_then(|v| v.as_str()),
            Some("a\n----\n")
        );
        assert_eq!(body, "B");
        assert!(split_frontmatter("---\nname: x\n").is_err());
        let (front, body) = split_frontmatter("No frontmatter").unwrap();
        assert!(front.is_empty() && body == "No frontmatter");
    }
}
